defaults:
  dataset: null
  network: ???

task: ???
data_name: ???

# ====== Utils ====== #
skip_eval: False
eval_ep: 1
eval_metrics: []
save_ep: 1
save_last: True
log_interval: 50
record_interval: 50

pretrained_ckpt: null
finetune_strategy: null

# ====== Network ====== #
network_wrapper:  # provide utilities for the main network
  target: lib.train.trainers.pose.pose_trainer.NetworkWrapper
  params:
    data_name: ${data_name}
    loss_weights: {}
    prox_annot: null
    train_extra_flip: False
    skip_spv_bi4s_seg: True  #  close this for performance

# ====== Train/Val Loader Settings ====== #
train:
  epoch: 30
  batch_size: 24
  num_workers: 8
  shuffle: True
  optimizer:
    optim: "adam"
    lr: 0.
    bs: ${train.batch_size}
    canonical_lr: 1.e-4
    canonical_bs: 32
    weight_decay: 0.0
    adamw_weight_decay: 0.01
  scheduler:
    type: 'multi_step'
    milestones: [15] 
    gamma: 0.5

val:
  batch_size: 64
  num_workers: 8
  shuffle: False
