defaults:
  network: configs/network/sahmr.yaml

task: sahmr_prox
data_name: prox_quant
pretrained_ckpt: datasymlinks/checkpoints/release/sahmr_prox_e30.pth

network:
  params:
    rc_cfg: {'hrnet_ver_name': 'metro_wo_pretrained'}
    m_ckpt: ""
