defaults:
  network: configs/network/sahmr.yaml

task: sahmr_rich
data_name: rich
pretrained_ckpt: datasymlinks/checkpoints/release/sahmr_rich_e30.pth

network:
  params:
    rc_cfg: {'hrnet_ver_name': 'metro_wo_pretrained'}
    m_ckpt: ""
